name: Node js app tester

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    # - name: Docker build and push
    #   uses: azure/docker-login@v1
    #   with:
    #       login-server: vehicleacrscn.azurecr.io
    #       username: ${{ secrets.REGISTRY_USERNAME }}
    #       password: ${{ secrets.REGISTRY_PASSWORD }}
    # - run: |
    #        docker buildx create --use --name multi-arch-builder
    #        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    #        docker buildx ls
    #        docker buildx build --platform linux/arm64 --push -t vehicleacrscn.azurecr.io/obdsignalgen:${{ github.run_number }} .
#           docker push vehicleacrscn.azurecr.io/obdsignalgen:${{ github.run_number }}
#           docker build . -t vehicleacrscn.azurecr.io/obdsignalgen:${{ github.sha }}
#           docker push vehicleacrscn.azurecr.io/obdsignalgen:${{ github.sha }}

    - name: Docker build and push
      uses: azure/docker-login@v1
      with:
          login-server: vehicleregistry.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
          docker build . -t vehicleregistry.azurecr.io/obdtester:${{ github.run_number }}
          docker push vvehicleregistry.azurecr.io/obdtester:${{ github.run_number }}
